[package]
name = "font-test-data"
version = "0.1.1"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Test data for the fontations crates"
repository = "https://github.com/googlefonts/fontations"
readme = "README.md"
categories = ["test data"]

# It is useful to publish this so tools that pull from crates can see it
#publish = false

# cargo-release settings
#[package.metadata.release]
#release = false
