# This is a 'codegen plan': it describes a series of steps to perform
# in order to regenerate all of this project's generated code.

# a list of directories that will be cleaned
clean = ["read-fonts/generated", "write-fonts/generated"]

# TODO: support a 'copy' step

# a mapping of files to generate, and their sources

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/colr.rs"
target = "read-fonts/generated/generated_colr.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cpal.rs"
target = "read-fonts/generated/generated_cpal.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/cpal.rs"
target = "write-fonts/generated/generated_cpal.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/font.rs"
target = "read-fonts/generated/font.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/font.rs"
target = "write-fonts/generated/generated_font.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/variations.rs"
target = "read-fonts/generated/generated_variations.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/variations.rs"
target = "write-fonts/generated/generated_variations.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/fvar.rs"
target = "read-fonts/generated/generated_fvar.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/fvar.rs"
target = "write-fonts/generated/generated_fvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/avar.rs"
target = "read-fonts/generated/generated_avar.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/avar.rs"
target = "write-fonts/generated/generated_avar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hvar.rs"
target = "read-fonts/generated/generated_hvar.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hvar.rs"
target = "write-fonts/generated/generated_hvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/vvar.rs"
target = "read-fonts/generated/generated_vvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/mvar.rs"
target = "read-fonts/generated/generated_mvar.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/mvar.rs"
target = "write-fonts/generated/generated_mvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/layout.rs"
target = "read-fonts/generated/generated_layout.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/layout.rs"
target = "write-fonts/generated/generated_layout.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gpos.rs"
target = "read-fonts/generated/generated_gpos.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gpos.rs"
target = "write-fonts/generated/generated_gpos.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gsub.rs"
target = "read-fonts/generated/generated_gsub.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gsub.rs"
target = "write-fonts/generated/generated_gsub.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cmap.rs"
target = "read-fonts/generated/generated_cmap.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/cmap.rs"
target = "write-fonts/generated/generated_cmap.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/head.rs"
target = "read-fonts/generated/generated_head.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/head.rs"
target = "write-fonts/generated/generated_head.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/name.rs"
target = "read-fonts/generated/generated_name.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/name.rs"
target = "write-fonts/generated/generated_name.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/post.rs"
target = "read-fonts/generated/generated_post.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/post.rs"
target = "write-fonts/generated/generated_post.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hhea.rs"
target = "read-fonts/generated/generated_hhea.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hhea.rs"
target = "write-fonts/generated/generated_hhea.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/vhea.rs"
target = "read-fonts/generated/generated_vhea.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/vhea.rs"
target = "write-fonts/generated/generated_vhea.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hmtx.rs"
target = "read-fonts/generated/generated_hmtx.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hmtx.rs"
target = "write-fonts/generated/generated_hmtx.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hdmx.rs"
target = "read-fonts/generated/generated_hdmx.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hdmx.rs"
target = "write-fonts/generated/generated_hdmx.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/vmtx.rs"
target = "read-fonts/generated/generated_vmtx.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/vmtx.rs"
target = "write-fonts/generated/generated_vmtx.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/vorg.rs"
target = "read-fonts/generated/generated_vorg.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/vorg.rs"
target = "write-fonts/generated/generated_vorg.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/maxp.rs"
target = "read-fonts/generated/generated_maxp.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/maxp.rs"
target = "write-fonts/generated/generated_maxp.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/meta.rs"
target = "read-fonts/generated/generated_meta.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/meta.rs"
target = "write-fonts/generated/generated_meta.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/stat.rs"
target = "read-fonts/generated/generated_stat.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/stat.rs"
target = "write-fonts/generated/generated_stat.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/os2.rs"
target = "read-fonts/generated/generated_os2.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/os2.rs"
target = "write-fonts/generated/generated_os2.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/glyf.rs"
target = "read-fonts/generated/generated_glyf.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gdef.rs"
target = "read-fonts/generated/generated_gdef.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gdef.rs"
target = "write-fonts/generated/generated_gdef.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gvar.rs"
target = "read-fonts/generated/generated_gvar.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gvar.rs"
target = "write-fonts/generated/generated_gvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cvar.rs"
target = "read-fonts/generated/generated_cvar.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/base.rs"
target = "read-fonts/generated/generated_base.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/base.rs"
target = "write-fonts/generated/generated_base.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cff.rs"
target = "read-fonts/generated/generated_cff.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/cff.rs"
target = "write-fonts/generated/generated_cff.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cff2.rs"
target = "read-fonts/generated/generated_cff2.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/cff2.rs"
target = "write-fonts/generated/generated_cff2.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/postscript.rs"
target = "read-fonts/generated/generated_postscript.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/postscript.rs"
target = "write-fonts/generated/generated_postscript.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/sbix.rs"
target = "read-fonts/generated/generated_sbix.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/sbix.rs"
target = "write-fonts/generated/generated_sbix.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/svg.rs"
target = "read-fonts/generated/generated_svg.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/bitmap.rs"
target = "read-fonts/generated/generated_bitmap.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/eblc.rs"
target = "read-fonts/generated/generated_eblc.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/ebdt.rs"
target = "read-fonts/generated/generated_ebdt.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cblc.rs"
target = "read-fonts/generated/generated_cblc.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cbdt.rs"
target = "read-fonts/generated/generated_cbdt.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gasp.rs"
target = "read-fonts/generated/generated_gasp.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gasp.rs"
target = "write-fonts/generated/generated_gasp.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/varc.rs"
target = "read-fonts/generated/generated_varc.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/aat.rs"
target = "read-fonts/generated/generated_aat.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/feat.rs"
target = "read-fonts/generated/generated_feat.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/ankr.rs"
target = "read-fonts/generated/generated_ankr.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/ltag.rs"
target = "read-fonts/generated/generated_ltag.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/ift.rs"
target = "read-fonts/generated/generated_ift.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/ift.rs"
target = "write-fonts/generated/generated_ift.rs"

# modules just used for testing
[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_offsets_arrays.rs"
target = "read-fonts/generated/generated_test_offsets_arrays.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_offsets_arrays.rs"
target = "write-fonts/generated/generated_test_offsets_arrays.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_records.rs"
target = "read-fonts/generated/generated_test_records.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_records.rs"
target = "write-fonts/generated/generated_test_records.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_formats.rs"
target = "read-fonts/generated/generated_test_formats.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_formats.rs"
target = "write-fonts/generated/generated_test_formats.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_flags.rs"
target = "read-fonts/generated/generated_test_flags.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_enum.rs"
target = "read-fonts/generated/generated_test_enum.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_enum.rs"
target = "write-fonts/generated/generated_test_enum.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_count_all.rs"
target = "read-fonts/generated/generated_test_count_all.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_conditions.rs"
target = "read-fonts/generated/generated_test_conditions.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_conditions.rs"
target = "write-fonts/generated/generated_test_conditions.rs"
