# This is a 'codegen plan': it describes a series of steps to perform
# in order to regenerate all of this project's generated code.

# a list of directories that will be cleaned
clean = []

# modules just used for testing

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_offsets_arrays.rs"
target = "read-fonts/generated/generated_test_offsets_arrays.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_offsets_arrays.rs"
target = "write-fonts/generated/generated_test_offsets_arrays.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_records.rs"
target = "read-fonts/generated/generated_test_records.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_records.rs"
target = "write-fonts/generated/generated_test_records.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_formats.rs"
target = "read-fonts/generated/generated_test_formats.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_formats.rs"
target = "write-fonts/generated/generated_test_formats.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_flags.rs"
target = "read-fonts/generated/generated_test_flags.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_enum.rs"
target = "read-fonts/generated/generated_test_enum.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_enum.rs"
target = "write-fonts/generated/generated_test_enum.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_conditions.rs"
target = "read-fonts/generated/generated_test_conditions.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_conditions.rs"
target = "write-fonts/generated/generated_test_conditions.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test_read_args.rs"
target = "read-fonts/generated/generated_test_read_args.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test_read_args.rs"
target = "write-fonts/generated/generated_test_read_args.rs"
